/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function jsco(sourceCode: string): Promise<any>
export declare function run(args: Array<string>): Promise<void>
